### PR TITLE
batik upgrade adjustments

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by mbiarnes** [comment]
@mswiderski tahnX - I will merge this and check this!

**Comment by mbiarnes** [comment]
@mswiderski fighting with this right now - this worked for you? without any error?

**Comment by mswiderski** [comment]
yes, no error at all, I even tried it on built kie server to make sure process instance image works as expected

**Comment by mbiarnes** [comment]
thanX

**Pull request merged**
